### ISSUE TITLE
failed to fill whole buffer

### ISSUE THREAD

**Issue by rtczza** [spicylobstergames/astratomic#60]
run cago run:

error:
```
WARN bevy_pbr::ssao: ScreenSpaceAmbientOcclusionPlugin not loaded. GPU lacks support: TextureFormat::R16Float does not support TextureUsages::STORAGE_BINDING.
...
thread 'Compute Task Pool (0)' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })', src/chunk_manager.rs:181:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `astratomic::chunk_manager::manager_setup`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```
kernel: `5.15.77-amd64-desktop`
rust:`rustc 1.72.0 (5680fa18f 2023-08-23)`

What causes it and how to fix it? Is it because there is no graphics card?

run  target/debug/astratomic：

```
...
WARN bevy_pbr::ssao: ScreenSpaceAmbientOcclusionPlugin not loaded. GPU lacks support: TextureFormat::R16Float does not support TextureUsages::STORAGE_BINDING.
ERROR bevy_asset::server: path not found: /home/astratomic/astratomic-0.2.0/target/debug/assets/atoms.ron
...
thread 'Compute Task Pool (2)' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })', src/chunk_manager.rs:181:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `astratomic::chunk_manager::manager_setup`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

**Comment by rtczza** [comment]
The source code is: v0.2.0.tar.gz

**Comment by Zac8668** [comment]
I think I got a similar error when I didn't had Vulkan installed, maybe that's it? We use bevy and it requires that, we probably need to add bevy requirements to our README

**Comment by Zac8668** [comment]
Here's bevy requirements: https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md

**Comment by Zac8668** [comment]
My guess is that you need to install one of these: 

> Depending on your graphics card, you may have to install one of the following: vulkan-radeon, vulkan-intel, or mesa-vulkan-drivers

**Comment by Zac8668** [comment]
I think I got it all wrong actually, sorry about that, it looks like it messed up the world file, if you delete the world file in `assets/world/` it will probably work again, but it will erase you word, sorry about that

**Comment by rtczza** [comment]
is works!
```
rm  assets/world/* 
cargo run 
```
then, you can run the game normally

thanks.
